package bpy.types.domainfluidsettings;
@:enum abstract Enum1(String) from String to String {
	var GEOMETRY : String = "GEOMETRY";
	var PREVIEW : String = "PREVIEW";
	var FINAL : String = "FINAL";
}@:enum abstract Enum2(String) from String to String {
	var NOSLIP : String = "NOSLIP";
	var PARTIALSLIP : String = "PARTIALSLIP";
	var FREESLIP : String = "FREESLIP";
}@:enum abstract Enum3(String) from String to String {
	var GEOMETRY : String = "GEOMETRY";
	var PREVIEW : String = "PREVIEW";
	var FINAL : String = "FINAL";
}/**
	Fluid simulation settings for the domain of a fluid simulation
**/
@:native("bpy.types.DomainFluidSettings") extern class DomainFluidSettings {
	/**
		Allowed compressibility due to gravitational force for standing fluid (directly affects simulation step size)
		
		Type: float in [0.001, 0.1], default 0.0
	**/
	var compressibility : Float;
	/**
		Simulation time of the last blender frame (in seconds)
		
		Type: float in [0, inf], default 0.0
	**/
	var end_time : Float;
	/**
		Directory (and/or filename prefix) to store baked fluid simulation files in
		
		Type: string, default “”, (never None)
	**/
	var filepath : String;
	/**
		Vertices of the fluid mesh generated by simulation
		
		Type: bpy_prop_collection of FluidVertexVelocity, (readonly)
	**/
	var fluid_mesh_vertices(default, never) : bpy.types.bpy_prop_collection.Bpy_prop_collection;
	/**
		Offset when reading baked cache
		
		Type: int in [-inf, inf], default 0
	**/
	var frame_offset : Int;
	/**
		Amount of particles to generate (0=off, 1=normal, &gt;1=more)
		
		Type: float in [0, 10], default 0.0
	**/
	var generate_particles : Float;
	/**
		Gravity in X, Y and Z direction
		
		Type: float array of 3 items in [-1000.1, 1000.1], default (0.0, 0.0, 0.0)
	**/
	var gravity : Array<Float>;
	/**
		Number of coarsened grids to use (-1 for automatic)
		
		Type: int in [-1, 4], default 0
	**/
	var grid_levels : Int;
	/**
		Estimated amount of memory needed for baking the domain
		
		Type: string, default “”, (readonly, never None)
	**/
	var memory_estimate(default, never) : String;
	/**
		Amount of mixing between no- and free-slip, 0 is no slip and 1 is free slip
		
		Type: float in [0, 1], default 0.0
	**/
	var partial_slip_factor : Float;
	/**
		Preview resolution in X,Y and Z direction
		
		Type: int in [1, 100], default 0
	**/
	var preview_resolution : Int;
	/**
		How to display the mesh for rendering
		
		Type: enum in [‘GEOMETRY’, ‘PREVIEW’, ‘FINAL’], default ‘GEOMETRY’
	**/
	var render_display_mode : bpy.types.domainfluidsettings.DomainFluidSettings.Enum1;
	/**
		Domain resolution in X,Y and Z direction
		
		Type: int in [1, 1024], default 0
	**/
	var resolution : Int;
	/**
		Fluid motion rate (0 = stationary, 1 = normal speed)
		
		Type: float in [0, 100], default 0.0
	**/
	var simulation_rate : Float;
	/**
		Size of the simulation domain in meters
		
		Type: float in [0.001, 10], default 0.0
	**/
	var simulation_scale : Float;
	/**
		
		
		Type: enum in [‘NOSLIP’, ‘PARTIALSLIP’, ‘FREESLIP’], default ‘NOSLIP’
	**/
	var slip_type : bpy.types.domainfluidsettings.DomainFluidSettings.Enum2;
	/**
		Simulation time of the first blender frame (in seconds)
		
		Type: float in [0, inf], default 0.0
	**/
	var start_time : Float;
	/**
		Amount of surface smoothing (a value of 0 is off, 1 is normal smoothing and more than 1 is extra smoothing)
		
		Type: float in [0, 5], default 0.0
	**/
	var surface_smooth : Float;
	/**
		Number of isosurface subdivisions (this is necessary for the inclusion of particles into the surface generation - WARNING: can lead to longer computation times !)
		
		Type: int in [0, 5], default 0
	**/
	var surface_subdivisions : Int;
	/**
		Override number of threads for the simulation, 0 is automatic
		
		Type: int in [0, 1024], default 0
	**/
	var threads : Int;
	/**
		Number of tracer particles to generate
		
		Type: int in [0, 10000], default 0
	**/
	var tracer_particles : Int;
	/**
		Reverse fluid frames
		
		Type: boolean, default False
	**/
	var use_reverse_frames : Bool;
	/**
		Generate speed vectors for vector blur
		
		Type: boolean, default False
	**/
	var use_speed_vectors : Bool;
	/**
		Removes the air gap between fluid surface and obstacles - WARNING: Can result in a dissolving surface in other areas
		
		Type: boolean, default False
	**/
	var use_surface_noobs : Bool;
	/**
		Use a custom start and end time (in seconds) instead of the scene’s timeline
		
		Type: boolean, default False
	**/
	var use_time_override : Bool;
	/**
		How to display the mesh in the viewport
		
		Type: enum in [‘GEOMETRY’, ‘PREVIEW’, ‘FINAL’], default ‘GEOMETRY’
	**/
	var viewport_display_mode : bpy.types.domainfluidsettings.DomainFluidSettings.Enum3;
	/**
		Viscosity setting: value that is multiplied by 10 to the power of (exponent*-1)
		
		Type: float in [0, 10], default 0.0
	**/
	var viscosity_base : Float;
	/**
		Negative exponent for the viscosity value (to simplify entering small values e.g. 5*10^-6)
		
		Type: int in [0, 10], default 0
	**/
	var viscosity_exponent : Int;
	/**
		
		@param id The RNA type identifier. — string
		
		@returns bpy.types.Struct subclass
	**/
	static function bl_rna_get_subclass(id:String):bpy.types.struct.Struct;
	/**
		
		@param id The RNA type identifier. — string
		
		@returns type
	**/
	static function bl_rna_get_subclass_py(id:String):Dynamic;
	/**
		Type of participation in the fluid simulation
		
		Type: enum in [‘NONE’, ‘DOMAIN’, ‘FLUID’, ‘OBSTACLE’, ‘INFLOW’, ‘OUTFLOW’, ‘PARTICLE’, ‘CONTROL’], default ‘NONE’
	**/
	var type : bpy.types.fluidsettings.FluidSettings.Enum1;
}