# Generated by Haxe 4.0.0-preview.4+1e3e5e0
# coding: utf-8



class blendertools_Plugin:
    __slots__ = ()


class ExamplePlugin:
    __slots__ = ()

    @staticmethod
    def register():
        print("Hello Blender! Registering Haxe module.")

    @staticmethod
    def unregister():
        print("Goodbye Blender! Unregistering Haxe module.")

    @staticmethod
    def main():
        pass


class python_internal_MethodClosure:
    __slots__ = ("obj", "func")

    def __init__(self,obj,func):
        self.obj = obj
        self.func = func

    def __call__(self,*args):
        return self.func(self.obj,*args)



ExamplePlugin.bl_info = "bl_info = {\n\t\"name\": \"Haxe Blender Plugin\",\n\t\"category\": \"User\",\n\t\"location\": \"Properties -> Render -> Haxy\",\n\t\"description\": \"Haxe Plugin for Blender\",\n\t\"author\": \"Zicklag<zicklag@katharostech.com>\",\n\t\"version\": (0, 1, 0),\n\t\"blender\": (2, 80, 0)\n}"

if __name__ == '__main__':
    ExamplePlugin.main()

# Global Data
bl_info = {
	"name": "Haxe Blender Plugin",
	"category": "User",
	"location": "Properties -> Render -> Haxy",
	"description": "Haxe Plugin for Blender",
	"author": "Zicklag<zicklag@katharostech.com>",
	"version": (0, 1, 0),
	"blender": (2, 80, 0)
}
register = ExamplePlugin.register
unregister = ExamplePlugin.unregister
